### ISSUE TITLE
Suitable replacement for old DAISY Pipeline "aligner"?

### ISSUE THREAD

**Issue by danielweck** [readbeyond/aeneas#1]
Great job @pettarin ! :)

CC @rdeltour @mgylling

I wonder if Aeneas could be integrated into the DAISY Pipeline (preferably v2).

https://github.com/daisy/pipeline-scripts

See the old DAISY Pipeline "aligner":

http://sourceforge.net/p/daisymfc/code/HEAD/tree/trunk/dmfc/transformers/se_tpb_aligner/

**Comment by readbeyond** [comment]
Nothing I can see impedes it from either a technical or a licensing point of view.

However, the best approach would be porting the DTW to Java, since the rest of the pipeline is in Java and you already have all the I/O code done.

Porting the DTW code to Java should be straightforward, and in theory it might also provide some speedup, depending which matrix library you choose. CMU Sphinx is now Java-based, so you are good on the MFCCs side as well.

The only concern I have is that the DTW approach is very hungry for memory and a run might take a long time if you feed in a long piece of audio. In my opinion the results are generally so good (on audiobook-like materials) that running the computation "in batch / in background" should not be a concern for the typical use case I can imagine, but deciding that is your (= DAISY) call.

**Comment by readbeyond** [comment]
Closing, as this is not really an "issue" with `aeneas`. If you (DAISY Consortium) want to discuss this more, please post on the mailing list, or reach me (Alberto) at my private email.
