### ISSUE TITLE
Regional Settings (i.e French) cause Errors in Aeneas 

### ISSUE THREAD

**Issue by erros84** [readbeyond/aeneas#162]
I'm using Aeneas through SIL's Scripture App Builder 3.2.
In Aeneas 1.7, and presumably 1.5, there is an error thrown when Windows has a regional setting that uses comma as a whole/part separator instead of period.

English:  $1,000.00
French : 1.000,00 $ or 1 000,00 $

![regional](https://cloud.githubusercontent.com/assets/986339/23330350/0d8ae57a-fb4c-11e6-91a0-d86fed24c91f.PNG)

It seems that a process in Aeneas uses the regional settings to create a timing value u'3,00', and then passes this back into a process that can't handle the comma.  

Steps to reproduce:
-Run Aeneas using an English regional setting to set a baseline.
It should work.
-Change the Regional Settings from English to something that uses a different decimal and group separator, -French (France), for example.
-Reboot.
Run Aeneas again, and watch it crash.

![sab error french regional error](https://cloud.githubusercontent.com/assets/986339/23330316/1659efd0-fb4b-11e6-8586-37c0a9ae54c8.PNG)

~Matthew

**Comment by readbeyond** [comment]
Hi,

thank you for letting me know about this issue.

aeneas itself does not handle localization settings. aeneas just expects 
values in seconds with a dot "." as the decimal separator.

I do not plan to add "locale support" in aeneas in the foreseeable 
future --- maybe in v2, but I think that such a feature should be dealt 
with by the user interface/client program that uses aeneas as a 
"library" for computing the audio/text alignment. After all, ISO 
mandates "." as the decimal separator, and "second" as time unit, etc.

I think this issue should be reported to SIL, since it is the 
Reading/Scripture App Builder program that produces the configuration 
string and invokes aeneas with it.

In fact, in your second screenshot you can see that the configuration 
string has:

is_audio_file_head_detect_max=3,00

(and also is_audio_file_head_detect_min=1,00)

with "," and not "." as aeneas expects.

I will close this issue as soon as I get back home, please report it to 
SIL: http://software.sil.org/readingappbuilder/support/

Does it make sense? Or do I miss something from your issue report?

AP

**Comment by erros84** [comment]
Your analysis seems correct, Thank you for your response, I have re-submitted on the Scripture App Builder JIRA.

**Comment by pettarin** [comment]
Alright, thank you.
