### ISSUE TITLE
Is there something wrong with my settings？

### ISSUE THREAD

**Issue by mr2coder** [readbeyond/aeneas#181]
![image](https://user-images.githubusercontent.com/17717209/27319453-1c665ef8-55c4-11e7-9f28-23523325e7bd.png)
why this happened？
in f000013，f000014... the output has the same begin and end？
and below is my code
thx.

# coding=utf-8

from aeneas.exacttiming import TimeValue
from aeneas.executetask import ExecuteTask
from aeneas.language import Language
from aeneas.syncmap import SyncMapFormat
from aeneas.task import Task
from aeneas.task import TaskConfiguration
from aeneas.textfile import TextFileFormat
import aeneas.globalconstants as gc

# create Task object
config = TaskConfiguration()
config[gc.PPN_TASK_LANGUAGE] = Language.ENG
config[gc.PPN_TASK_IS_TEXT_FILE_FORMAT] = TextFileFormat.PLAIN
config[gc.PPN_TASK_OS_FILE_FORMAT] = SyncMapFormat.JSON
task = Task()
task.configuration = config
task.audio_file_path_absolute = u"audio.wav"
task.text_file_path_absolute = u"plain.txt"

# process Task
ExecuteTask(task).execute()

# print produced sync map
print(task.sync_map)

**Comment by readbeyond** [comment]
It is hard to tell without knowing the kind of audio and the text you 
are trying to synchronize.

In general, zero-length fragments might happen, and the reason is either:

1. the corresponding text fragment has zero length (empty string)

or

2. the text and the speech are significantly different (e.g., the audio 
contains a whole sentence more than the text, or vice versa)

or

3. if towards the begin/end, the audio contains a head or tail made of 
music or other non-speech sound.

In cases 1 or 2 the solution is to edit your text appropriately. In case 
3 you can specify the length of the head/tail to be ignored for 
alignment purposes.

Also note that there is a parameter that you can add to your task config 
string ( "task_adjust_boundary_no_zero=True" ) or object ( 
config[gc.PPN_TASK_ADJUST_BOUNDARY_NO_ZERO] = True ), that will add 
0.001 s to zero-length fragments. This is useful if you must ensure that 
no fragment has zero length (e.g., it is not allowed by the EPUB SMIL 
specification), but of course it will not solve any "logic" issue like 
1-2-3 above.

Finally, it might be that the algorithmic approach of aeneas is not 
suitable for your particular audio/text or language.

Please check if your case is 1, 2, or 3. If not, and you really need 
help, please send me privately your audio/text files via email, and I 
will have a look at them.

Alberto Pettarin

**Comment by onsunsl** [comment]
@readbeyond ：
I think error lines are: f000013 to f000016， Their begin and end times are the 45.320.
I also encountered the same problem：word and audio are not aligned.

**Comment by shairoz** [comment]
same error, solved by downgrading to previous release (1.7.0)
