### ISSUE TITLE
Help: are there ways to align boundary of  voice to boundary of sentences?

### ISSUE THREAD

**Issue by jarodtang** [readbeyond/aeneas#219]
Hi there,

I got two sentences, and found part of sentence 2's voice be aligned to sentence 1, are there any ways to force align group of voice accordingly?

Regars,
Jarod

![q2](https://user-images.githubusercontent.com/5282236/47330891-6b6fad00-d6ac-11e8-9b44-3282b153a9ac.jpg)

**Comment by readbeyond** [comment]
Your "group2" onset is weak, hence I guess it is detected as silence because it does not pass the (default) energy threshold of the VAD.

See the VAD_* parameters of the RuntimeConfiguration: https://www.readbeyond.it/aeneas/docs/runtimeconfiguration.html#aeneas.runtimeconfiguration.RuntimeConfiguration.VAD_EXTEND_SPEECH_INTERVAL_AFTER

In alternative, you can try reducing the default MFCC window shift, and see if it helps.

**Comment by jarodtang** [comment]
I tried both VAD and MFCC, which didn't solve the problem.

> rconf[RuntimeConfiguration.VAD_LOG_ENERGY_THRESHOLD] = 0.100
