### ISSUE TITLE
VAD options. Can I change them? 

### ISSUE THREAD

**Issue by ApayRus** [readbeyond/aeneas#259]
Hi! Thank you for your greatest library. I so love it and use it last weeks! :) 
I runned `vad` and got file with `speach`, `nonespeach` intervals. 
Then I visualized it in `Audacity` by  "import --> labels". (track 1) 

Also I runned Audacity `analyze --> sound finder` with different params and got track 2 and 3. 

![vad-lost](https://user-images.githubusercontent.com/1222611/87865289-011c9700-c97c-11ea-876a-c4f8c2698d96.png)

How we can see, `Aeneas/vad` eats parts of speech, but  `Audacity/sound finder` don't , and works properly. 
Is there a way to change `Aeneas/vad` parameters, how we can change them in `Audacity/sound finder`? 

![Screenshot from 2020-07-19 04-45-20](https://user-images.githubusercontent.com/1222611/87865290-0bd72c00-c97c-11ea-913d-5ed995254e08.png)

If you ask me, why I need this... I want to add gaps between phrases. Aeneas marks phrases in that way (without gaps):

![Screenshot from 2020-07-19 05-05-51](https://user-images.githubusercontent.com/1222611/87865422-c9aeea00-c97d-11ea-89ab-aca91b9b1949.png)

I need phrases in that way (with gaps): 

![Screenshot from 2020-07-19 05-05-00](https://user-images.githubusercontent.com/1222611/87865428-d6334280-c97d-11ea-83c4-8f5ecd360632.png)

Also you can take a look at my site where I implement all this things [frazy.me](https://frazy.me)

**Comment by readbeyond** [comment]
@Aparus you can tweak the VAD included in aeneas:

- https://www.readbeyond.it/aeneas/docs/vad.html
- https://www.readbeyond.it/aeneas/docs/runtimeconfiguration.html#aeneas.runtimeconfiguration.RuntimeConfiguration.VAD_EXTEND_SPEECH_INTERVAL_AFTER

and also the way the boundaries are set:

- https://www.readbeyond.it/aeneas/docs/adjustboundaryalgorithm.html

but the raw truth is that the VAD included in aeneas is very rough (just compares the spectral energy). The VAD included in Audacity probably works better because it implements a better algorithm.

Currently there is no way of hooking in a different VAD implementation, you would need to run aeneas from source (e.g., from an editable installation) and change vad.py yourself.

In the past, I tried the WebRTC via https://github.com/wiseman/py-webrtcvad  but it has some limitations/problems, so I did not integrate it in aeneas "open source".

I might consider supporting a better VAD or even allowing users to hook-in custom VADs  in aeneas 2.0.0, but that will not happen any time soon.
