### ISSUE TITLE
Expose additional eSpeak voices

### ISSUE THREAD

**Issue by djones1844** [readbeyond/aeneas#33]
Currently the languages allowed by the validation process are a subset of the voices available to espeak. Could we add the rest, or at least the english variations such as en-gb and en-us?

**Comment by readbeyond** [comment]
From my tests, using (say) `en` instead of (say) `en-gb` does not affect the final alignment significantly (if at all?).

But I agree that it makes little sense listing only a subset of the espeak voices. In the next release I will list all the current espeak voices.

BTW, you can already specify a voice not listed in `language.py`, e.g. `en-gb`: just pass the `--skip-validator` flag to `aeneas.tools.execute_task` or `aeneas.tools.execute_job`. (This mechanism indeed allows using aeneas with espeak voices built by the user or the regional variants like `en-gb`.) For example:

```
$ CONFIG_STRING="task_language=en-gb|is_text_type=plain|os_task_file_format=json"
$ python -m aeneas.tools.execute_task aeneas/tools/res/audio.mp3 aeneas/tools/res/plain.txt "$CONFIG_STRING" output/sonnet.json --skip-validator
```

**Comment by readbeyond** [comment]
I forgot to ask, just to understand better your use case: did you find that using `en-gb` yields different results than `en` on your own materials or did you ask that for "cosmetic" reasons?

**Comment by djones1844** [comment]
I've tested several of our documents and the alignment accuracy is significantly improved by using the "en-gb" instead of the standard "en".

**Comment by pettarin** [comment]
Interesting, thank you for sharing your insight! I will try to release a minor release tomorrow, with the full list of espeak voices.
