### ISSUE TITLE
Packaging for OSX

### ISSUE THREAD

**Issue by chrisvire** [readbeyond/aeneas#86]
At SIL, we are working on releasing Scripture App Builder for Mac (will build Android and iOS apps).  We would like to include Aeneas support on the Mac.  I have been in discussion with @danielbair on creating a package for OSX.  Would you accept a pull request for this (similar to the debian packaging) or should we keep it as a separate repo?

Thanks,

Chris

**Comment by readbeyond** [comment]
Hi Chris.

I am not familiar with packaging for OS X, but if it is something similar to deb packaging (that is, just some manifest/license/changelog/etc. files), then you can directly open a pull request towards the master branch, and I will merge it.

If technically possible, put the files into a osx/ directory, in a fashion similar to the current debian/ directory.

Thank you for your help.

**Comment by pettarin** [comment]
@chrisvire FYI, I am investigating using pyinstaller to create single-file executables, especially for Windows as Richard Margetts let me know that the biggest issue for your Windows users is indeed the setup procedure for aeneas. I am not sure whether this (= pyinstaller) might be an interesting route for OS X as well, or if a more "Debian-like" way is easier and/or preferred for OS X. I am open to any solution that works for you/your users.

**Comment by chrisvire** [comment]
@danielbair came up with a solution for OSX.  We will figure out how to document and submit a PR.  Indeed, users struggle with installation of all the component for Aeneas.  The love the end results! So something more "Debian-like" would be welcome to Windows users.

**Comment by chrisvire** [comment]
@pettarin, we decided to create a third-party installer instead of including it in the main repository.  @danielbair created worked on installers for both Mac and Windows.  They include everything needed: Python 2.7, ffmpeg, espeak, and dependent libraries.

https://github.com/sillsdev/aeneas-installer

**Comment by readbeyond** [comment]
Great news!

Thank you for letting me know. I guess you (SIL) is going to provide those installers through the (SAB/RAB?) Web site --- if (or when) you have a URL, I will be glad to update the aeneas docs to point users to them.

**Comment by chrisvire** [comment]
FYI, since @danielbair did a great job on the Mac installer, I asked him to look at the Windows installer.  I didn't know that @rpmargetts had requested that you look into packaging aeneas using pyinstaller.  He told me that he would be more interested with the results that you are achieving.

Does the work with pyinstaller work on multiple platforms or is it Windows only?  

We have not "released" the Mac (or Windows) installer or versions of SAB/RAB that work with them.  The Mac SAB/RAB and Aeneas Installer which work together are accessible only to Beta users.

**Comment by readbeyond** [comment]
No problem.

pyinstaller can create a single executable of aeneas (or an "exploded" directory with the actual executable and the library files) on Linux, Windows and OS X. However, it will not include ffmpeg or eSpeak, and you need to create different EXE files for 32/64 bit OSes.

I am copy-pasting from the email I sent to Richard about an hour ago.
=== === ===

To create the aeneas-cli.exe, on your Windows machine:

A. Install pyinstaller v3.1.1 (I had issues with v3.2):

pip install pyinstaller==3.1.1

B. Install UPX:

http://upx.sourceforge.net/

(this step is optional, but UPX significantly reduces the EXE size, so better having it)

C. Clone my personal devel/ branch:

https://github.com/pettarin/aeneas/tree/devel

(If all go well, I will push to readbeyond's repo later.)

D. Compile the Python C extensions as usual:

python setup.py build_ext --inplace

Note that pyinstaller do NOT compile the C extensions. However, if the already-compiled .pyd files are found in the aeneas/ dir, they are bundled in the EXE, and the resulting EXE will use them (hence, it will run fast).

E. Create the EXE:

pyinstaller pyinstaller-onefile.spec --upx-dir c:\PATH\TO\UPX

You should get a aeneas-cli.exe file in the dist/ directory. This EXE is the hydra script (pyinstaller-aeneas-cli.py in the repo root dir). The synopsis is:

aeneas-cli.exe [TOOL] [TOOL ARGUMENTS]

For example:

aeneas-cli.exe --execute-task AUDIO TEXT CONF OUTPUT
aeneas-cli.exe --execute-job JOB.ZIP OUTPUT

Note that "--execute-task" is the default tool, so:

aeneas-cli.exe --execute-task AUDIO TEXT CONF OUTPUT

and

aeneas-cli.exe AUDIO TEXT CONF OUTPUT

are equivalent. The built-in examples should work too, e.g.:

aeneas-cli.exe --execute-task --example-smil

=== === ===

Notes:

a. pyinstaller takes care of the aeneas/Python/C extensions stuff only. The user still has to install FFMPEG and eSpeak separately.

b. pyinstaller can either package a single EXE or create a directory with several files in it ("program directory"). At runtime, the "single EXE" option is slower than the "directory" option by 10-20 seconds, because it unpacks the files at each execution. The disadvantage of the "directory" approach is that you need to ZIP the directory, make your users download the ZIP and instruct them to UNZIP it. With the single EXE option, on the other hand, they have to download and run just one file. See what it is better/easier for your users. If you want the directory approach, use "pyinstaller-onedir.spec" instead of "pyinstaller-onefile.spec".

c. As mentioned before, pyinstaller creates an EXE specific for the OS and 32/64 bits. I believe --- but I cannot confirm --- that an EXE created on a (say) 64bit Windows 10 machine will work on a (say) 64bit Windows 7 machine, etc. If you can, try to test it.

d. Always remove the build/ and dist/ directories before running pyinstaller --- I lost a lot of time debugging issues due to the fact that it caches things there.

e. The same *.spec files can be used for bundling on OS X. (Again, not having two OS X machines, I cannot confirm it actually works.)

**Comment by danielbair** [comment]
I have a few questions about packaging aeneas.

Richard's instructions for installing on Windows state that numpy must be
downgraded to 1.10.* because of a bug with aeneas and numpy? Is this still
necessary?

Also, can aeneas.cew be compiled for Mac and Windows yet? I thought I had
seen something mentioning it was possible. This would allow Windows and Mac
users to enjoy similar speeds as Linux users. I'm willing to work on this
since we are now creating an installer bundle for the end user.

I have not worked with pyinstaller before (I was simply making python wheel
packages for aeneas and its dependencies and installing them on the user's
machine with pip), but it appears that the directory approach will work
best for performance and should be no problem to include in
Aeneas_Installer bundle with FFmpeg and eSpeak.

Also, will a pyinstaller package compiled for 32bit work on a 64bit
machine? The Aeneas_Installer so far has been build for 32bit and works
fine on 64bit.

As far as testing on Mac OS X or MS Windows, I have just been using
Parallels virtual machines on my MacBook Pro.





[image:
https://lh4.googleusercontent.com/-wIrA61rE_y4/AAAAAAAAAAI/AAAAAAAAAAA/EadW_TiIByg/s64-c/photo.jpg]
Daniel Bair, Director, Thailand Gospel Media Project
| m. 081-362-1520 | h. 817-264-6456 | o. 053-995-453
| e. missions@danielbair.com | w. missions.danielbair.com

**Comment by readbeyond** [comment]
In order:

1. numpy==1.10.x => the problem was with numpy 1.11.x packaged by Continuum (conda), which caused errors. aeneas works with any numpy >= 1.9 (installed via pip or compiled from source).

2. I have aeneas.cew on Windows and OS X, yes. Unlike on Linux, where setuptools can build the Python C extension by dynamically linking to a shared library (libespeak.*.so) which is conveniently installed in a system place (/usr/something...) by the OS package manager, on Windows and OS X there is no such a shared library. Hence:

* on OS X, I compiled eSpeak from source, and modified the cew_setup.py to link statically against libespeak.a => from a technical point of view, since all recent Macs are 64bit, one could just distribute this .a (provided the legal details are cleared), and have python setup.py work as on Linux;
* on Windows, I had to grab the .dll shipped by eSpeak, and then manually tweak and place the resulting cew.pyd somewhere in the Python installation directory because otherwise Python could not import the cew module --- I do not remember the details right now, I would need to look them up from my notes. I remember it was a dirty process, difficult to automate without assuming that Python is installed in a specific directory, at least from my knowledge of Python on Windows (which is little).

3. In theory, pyinstaller only ensures that the executable built on a platform (OS, 32/64 bit) can run on the same platform. In practice:

* on Linux, the 32bit vs 64bit executables are incompatible, I have proof of that;
* on Windows, I believe the "emulation mode" will make a 32bit EXE run on a 64bit machine, while I doubt the opposite is possible;
* on OS X, since the Intel-based Macs are all 64 bit machines (except the very first Core Solo and Core Duo), I think it is worth producing only the 64bit executable.
